spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: "rootpass^^*"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
        threads: 4
        nettyThreads: 4
grpc:
  clients:
    shipment:
      address: "grpc-server:6565"
      negotiationType: plaintext
      enableKeepAlive: true

api:
  version: "2025-06-15"

uuid:
  node-id: ${NODE_ID:0}

server:
  port: 9095
