spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: rootpass^^*
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
        threads: 4
        nettyThreads: 4

api:
  version: "2025-06-15"

uuid:
  node-id: ${NODE_ID:0}

server:
  port: 9093
