spring:
  datasource:
    url: jdbc:mysql://mysql:3306/order_db
    username: root
    password: rootpass^^*
  kafka:
    bootstrap-servers: kafka:29092

api:
  version: '2025-05-25'

uuid:
  node-id: ${NODE_ID:0}