spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: pass
  kafka:
    bootstrap-servers: localhost:9092

api:
  version: '2025-05-25'

server:
  port: 8083