spring:
  datasource:
    url: jdbc:mysql://mysql:3306/product_db
    username: root
    password: rootpass^^*
  kafka:
    bootstrap-servers: kafka:29092
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
        threads: 4
        nettyThreads: 4
api:
  version: '2025-05-25'

uuid:
  node-id: ${NODE_ID:0}