spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: "rootpass^^*"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
grpc:
  clients:
    shipment:
      address: static://"grpc-server:6565"
      negotiationType: plaintext
      enableKeepAlive: true
